services:
  postgres:
    container_name: postgres-sql-email
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      #DARLE UN NAME A LA BASE DE DATOS Y SE CREARA AUTOMATICAMENTE
      POSTGRES_DB: email_social_jwt
    volumes:
      - postgres:/data/postgres
    ports:
      - 5435:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-jwt-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge
volumes:
  postgres:
    driver: local